### ISSUE TITLE
define default values in readme.md

### ISSUE THREAD

**Issue by JoernBerkefeld** [fib-at-isobar/beautyAmp#1]
hi there, happy that you picked this up - I've gone the easy way with a prettier+eslint+eslint config combo to get SSJS going but ampscript was kinda the white wale so far.

With that said, could you please update the readme so it states what the default config values are?

**Comment by JoernBerkefeld** [comment]
also, maybe state how it's activated. for *.amp files? for *.html files?

**Comment by fib-at-isobar** [comment]
Hello Jörn,
thanks for the attention! I will try to solve your comments ASAP.

Right now, you can find the defaults on "Feature Contributions" Tab in the Extension page (inside VSCode).
I will answer the "activation" in your other issue #2

**Comment by JoernBerkefeld** [comment]
fair point, didnt notice the feature contribution section. adding it to the readme.md could help nonetheless as it's otherwise not visible on github

**Comment by fib-at-isobar** [comment]
Sorry, I will only add a note where you can find it. I don't want to confuse users in case I would do a change and forgot to change it in the README.
Once you are on the GitHub you can always look it up in the `package.json`.

**Comment by fib-at-isobar** [comment]
Solved in release 0.3.1
