### ISSUE TITLE
Unable to install on VS Code (version 1.40.2).

### ISSUE THREAD

**Issue by mackgr-dev** [fib-at-isobar/beautyAmp#10]
>_Unable to install 'fib.beautyamp' extension because it is not compatible with the current version of VS Code (version 1.40.2)._

Any ideas? 

I look forward to trying it out. Thank you!

**Comment by fib-at-isobar** [comment]
Hello @mackgr-dev,
please, upgrade you VS Code, as your version is more than one year old.
Current version is `1.55.1`. The lowest supported version is cca `1.43`.
I prefer not to lower the minimal required version as it would make it more difficult to support the extension.
Regards,
Filip
