### ISSUE TITLE
no manual formatting command?

### ISSUE THREAD

**Issue by JoernBerkefeld** [fib-at-isobar/beautyAmp#2]
CTRL+SHIFT+P opens the available commmands but i couldnt find a command for this being published. 

it started working though once i renamed the file to use the .amp extension. What also worked was changing the type through the selection on the lower right corner.

I did notice that it adheres to VSCode setting  `"editor.formatOnSave": false/true` --> would be cool to mention that in the docs as well

**Comment by fib-at-isobar** [comment]
The extension is using standard "format document" command. This is why I did not mention it.
But I will add the steps with a GIF.
So:

1. mark you file as AMPscript (either by using `.amp` file suffix) or using the `Language Mode`
2. Run the `Format Document` command (either using right-click or aforementioned the CTRL+SHIFT+P shortcut).

**Comment by fib-at-isobar** [comment]
Information added in release 0.3.1.
