### ISSUE TITLE
Formatting replaced closing quote with closing bracket

### ISSUE THREAD

**Issue by JoernBerkefeld** [fib-at-isobar/beautyAmp#3]
```
%%[
    SET @Title = IIF(EMPTY(@Title) OR @Title=='Without title' OR @Title=='Unknown' OR @Title=='Untitled', '', Concat(' ',@Title))
]%%
``` 
was turned into
```
%%[
	SET @Title = IIF(EMPTY(@Title) OR @Title=='Without title' OR @Title=='Unknown' OR @Title=='Untitled), '', Concat(' ', @Title))
]%%
```

means that it **removed** the closing quote behind **@Title=='Untitled** and replaced it with a **)**.

**Comment by fib-at-isobar** [comment]
Hello Jörn,
I've identified the bug: it's a regex which splits the function into its individual parameters.
I am working on the fix. This will be part of the next release.

**Comment by fib-at-isobar** [comment]
Hello Jörn,
I've fixed the bug and improved the whole method formatting.
Thanks for bringing it up!
