### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by JoernBerkefeld** [fib-at-isobar/beautyAmp#5]
right now you don't specify how this extension may be used - or re-used, preventing me and other from forking this and spending time on fixing things. Also, once it works a bit more reliably, I'd love to include it as a recommendation in some of my plugins/extensions but without knowing what rights you grant that's a no-go.

**Comment by fib-at-isobar** [comment]
You are right. And here I thought I've added that. Will fix with next release.

**Comment by fib-at-isobar** [comment]
Initial license added.
