### ISSUE TITLE
multi-line comments are collapsed

### ISSUE THREAD

**Issue by JoernBerkefeld** [fib-at-isobar/beautyAmp#6]
when writing sth like the following:
```
/*
* example on how to use this 
* example on how to use this
*/
```
it gets rewritten to
```
	/* * example on how to use this  * example on how to use this */
```

expectation would be that comments are merely indented but not changed otherwise

**Comment by fib-at-isobar** [comment]
True! I will fix it in one of the next versions.

**Comment by JoernBerkefeld** [comment]
any update? ;-)

**Comment by fib-at-isobar** [comment]
Not yet, unfortunately I've got more urgent projects at the moment. :(
But don't worry, it's in the Todo.

**Comment by fib-at-isobar** [comment]
Hello Jörn,
I am currently testing a new version (1.3.2) which should fix the problem.
I've included it in the repository (as VSIX), so feel free to try it out and tell me, whether you are happy with the fix (for this, and the Tabs/Spaces problems).
Regards,
Filip

**Comment by JoernBerkefeld** [comment]
0.3.2, right?
tried this just now and the bug seems fixed, good job!

I did notice one thing though: **prettier** would format multi-line comments that are prefixed slightly differently:

![image](https://user-images.githubusercontent.com/1917227/97584352-38c5c100-19f8-11eb-9762-8489600dface.png)
see how it adds 1 space in 2 out of those 3 cases? would be nice to mirror that behavior

**Comment by fib-at-isobar** [comment]
Hello,
thanks for testing it.
I will not be able to do this in the next couple of weeks. So I would propose this: I will release v0.3.2 and close this issue.
And you can create a new issue, for handling this as an improvement.
Do you agree?

**Comment by JoernBerkefeld** [comment]
Good idea!

Jörn @mobile

Filip <notifications@github.com> schrieb am Do., 29. Okt. 2020, 14:12:

**Comment by fib-at-isobar** [comment]
Closing this issue, as the initial bug was solved. And opened a new enhancement task to handle your improvement later on.
