### ISSUE TITLE
Access formatting via CLI?

### ISSUE THREAD

**Issue by JoernBerkefeld** [fib-at-isobar/beautyAmp#8]
Hi there, me again ;-)

would you be open to splitting the core beautify library into a separate repo? I'd like to programmatically format AMPscript, meaning, via nodejs method that takes a string and then outputs the formatted version of it.

Thanks
Jörn

**Comment by fib-at-isobar** [comment]
Hey!
Nice to hear from you again, Jorn!
That looks like a great idea! And it would actually allow doing the same for Atom as well.
I will try to do this with the release, but I am busy for now, so it will take time.
Cheers!
Filip

**Comment by fib-at-isobar** [comment]
Hello @JoernBerkefeld,
I am currently working on this feature.
Regards,
Filip

**Comment by JoernBerkefeld** [comment]
that would be really cool! we'd use your package in https://github.com/Accenture/sfmc-devtools if you did <3

**Comment by fib-at-isobar** [comment]
Hello @JoernBerkefeld ,
It's here! First public version of the library is on NPM: https://www.npmjs.com/package/beauty-amp-core (and on git: https://github.com/fib-at-isobar/beautyAmpCore)
Please, consider the same licence as for the main package.

Regards,

Filip

**Comment by JoernBerkefeld** [comment]
just a thought: if you add the info into your package.json, it shows up on the npm page:


    "license": "MIT",
    "repository": {
        "type": "git",
        "url": "https://github.com/Accenture/sfmc-devtools.git"
    },
    "homepage": "https://github.com/Accenture/sfmc-devtools#readme",
    
    
![image](https://user-images.githubusercontent.com/1917227/127155707-efc05f3d-5b0b-4b19-a949-9c4be2c28654.png)

afterwards you will need to increase your version at least by +1 patch though

**Comment by fib-at-isobar** [comment]
Thanks! I will do this in a bit :)

**Comment by JoernBerkefeld** [comment]
also, 
> npm install readme -g

i believe that's a copy-paste error :)

**Comment by fib-at-isobar** [comment]
Yeah... Already fixed it on my end, but will publish the module with more changes.
